/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#40000c",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-primary-container": "#a9a7ff",
        "background": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#005137",
        "on-secondary-fixed": "#002114",
        "surface-container": "#e5eeff",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed-dim": "#68dba9",
        "on-surface-variant": "#464553",
        "outline-variant": "#c8c4d5",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "tertiary-container": "#8a0025",
        "inverse-surface": "#213145",
        "outline": "#777584",
        "on-primary-fixed-variant": "#3b35a7",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#ff8f96",
        "tertiary-fixed": "#ffdada",
        "on-secondary-container": "#00714e",
        "inverse-primary": "#c3c0ff",
        "error": "#ba1a1a",
        "primary": "#1f108e",
        "secondary-container": "#82f5c1",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary": "#ffffff",
        "tertiary": "#600017",
        "surface-container-low": "#eff4ff",
        "secondary": "#006c4a",
        "secondary-fixed": "#85f8c4",
        "on-tertiary-fixed-variant": "#920028",
        "primary-container": "#3730a3",
        "on-surface": "#0b1c30",
        "surface-tint": "#544fc0",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      boxShadow: {
        'subtle': '0 1px 2px 0 rgba(0, 0, 0, 0.03)',
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.03)',
        'elevated': '0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -4px rgba(0, 0, 0, 0.03)',
      },
      spacing: {
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ['"Plus Jakarta Sans"', "Inter", "sans-serif"],
        "serif": ['"Newsreader"', "Georgia", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
